### ISSUE TITLE
composer memory limit

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/manual#110]
Problem:
> Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php
on line 223 

> Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

Lösung:
> COMPOSER_MEMORY_LIMIT=-1 php /usr/local/bin/composer install
> 
> Durch die Verwendung von COMPOSER_MEMORY_LIMIT=-1 stellen Sie sicher, dass der PHP-Prozess nicht mehr Speicher als der im Parameter memory_limit zugewiesene verbraucht.

**Comment by jonmz** [comment]
I'm not sure if this is correct. First of all:
> Note: Composer internally increases the `memory_limit` to 1.5G.
So a `memory_limit` less than that is already ignored. (That's why the error message shown above refers to 1610612736 bytes which is already higher than the `memory_limit` set by us.)

Second: The value of "-1" means _unsetting_ `memory_limit`. In this case, users will run against the CGroup memory limit which is _also_ 1.5G so I don't think this situation can be solved at all. I would be surprised if `COMPOSER_MEMORY_LIMIT=-1` would be able to solve this because the CGroup limit cannot be overridden by users.

**Comment by medienverbinder** [comment]
Somehow it looks like the composer does not accept the memory limitation either?

According to the documentation (https://getcomposer.org/doc/articles/troubleshooting.md) this should work:

`COMPOSER_MEMORY_LIMIT=1500M php /usr/local/bin/composer install`

I have tested it, but that also throws a fatal error.

**Comment by luto** [comment]
The docs only mention disabling the limit using `COMPOSER_MEMORY_LIMIT`. Composer doesn't seem to honor smaller limits.

**Comment by selamhabibi** [comment]
That's not entirely true.

"COMPOSER_MEMORY_LIMIT" sets the "memory_limit" to the passed value.

=> https://github.com/composer/composer/blob/28f0d8fcf7e2d6cb207b3c6ceca0e6142d141a7f/bin/composer#L46-L56

Anyway...it doesn't work :-(

**Comment by jonmz** [comment]
The thing is: composer needs as much memory as it needs - you cannot tell him "please use just 700M" and then it magically just uses 700M; that's not how this works. If composer _needs_ e.g. 2G of memory, the only solution is to _provide_ it with those 2G - which is impossible on our current resource limit strategy which has the user's CGroup limited to 1.5G.

**Comment by medienverbinder** [comment]
No magic... too bad! ;-)

But seriously...with this it will be hard to realize (PHP) projects on Uberspace 7. For example the development of Drupal8 projects is not really possible if the Composer does not work.

Maybe this fact should at least be written to the manual? (This saves other users at least the trouble shooting)

Thanks a lot!

**Comment by jonmz** [comment]
composer at least _used_ to work fine, and its increased memory usage may be a fact that might get lowered again in a future release.

My personal opinion is that a _package manager_ needing 1.5G just for things like dependency resolving seems _ridiculous_. No other package manager like npm for node.js or Bundler for ruby or cpanm for Perl or pip for Python needs that much memory - not in the slightest.

Another fun fact is that Drupal 8 itself seems to run fine with values [as low as 128M or 256M](https://www.drupal.org/docs/8/system-requirements/php-requirements#settings_required) - but for the _installation_ you need 6-12 times that amount of memory?

[Others have written about this](https://www.jeffgeerling.com/blog/2018/make-composer-operations-drupal-way-faster-and-easier-on-ram) ("Requiring over 1 GB of RAM to do even a simple composer require for a barebones Drupal site is kind-of insane, IMO"), pointing to [this Drupal extension](https://github.com/zaporylie/composer-drupal-optimizations) to reduce the amount of memory needed by composer.

Other projects like Pimcore are also observing that [even providing 3G simply isn't enough](https://github.com/pimcore/pimcore/issues/3255), and here's a nice [issue in the composer repo itself](https://github.com/composer/composer/issues/5915):

> It has been a very long-time standing fact that the update process requires a lot of memory. The bigger your dependency graph gets, the more rules Composer has to create for the solver to analyze. Narrowing constraints, not including dev dependencies, upgrading to php 7, these are all ways to reduce the memory footprint. But on large applications it is virtually impossible to get below 1Gb for update operations. There is not much we can do about this, unless you can find us some brilliant scientist/math geek who also happens to understand php and can help us optimize/rewrite the solver, and would happily do so free of charge. Good luck with that.. :p

I truly hope for the composer community to find some better solution for this. Throwing a _ridiculous_ amount of memory onto the problem seems no real solution for me.

We are _thinking_ about a workaround that lets users raise their CGroups maximum memory _for a while_ (like, 1h) and to make sure that not too many users do that at the same time - and not repeatedly. Our systems are still running on shared resources; it would be impossible (from the financial aspects, not from the technical ones) to generally provide users with a lot more of memory.

**Comment by medienverbinder** [comment]
Yes, there are suspiciously many issues about "composer & memory" on the project page. But I am confident that this will change in v2...at least that's what it sounds like ;-)

I can only agree with you about the memory requirements of the Composer...I have not experienced anything similar with other package managers.

I already considered the plugin "zaporylie/composer-drupal-optimizations", but funnily enough the composer exits at this point and the composer profiling says:

```
[545.5MiB/9.68s] Reading /.cache/composer/repo/https---repo.packagist.org/provider-zaporylie$composer-drupal-optimizations.json from cache

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

(that's quite a leap in memory, isn't it?)

Well...in the end, all that remains is to adapt the workflow accordingly and to enter all relevant changes on a development system and play them out on the production system via "composer.lock".
