### ISSUE TITLE
document .qmail

### ISSUE THREAD

**Issue by luto** [Uberspace/manual#12]
Give users an overview how to manage email addresses / aliases with .qmail files:

- what is qmail? (is fairly non-standard, so explain it)
- how do I forward my primary mail address to something external? to another address (hello@ => hallo@)?
- how do I forward secondary mailboxes? to another address? (link to vmailmgr)
- how do I drop all mail to an address?
- how do I configure a wildcard box?

**Comment by luto** [comment]
Also see https://wiki.uberspace.de/mail:dotqmail.

**Comment by ehlers** [comment]
I suggest to document maildrop as well. Like .qmail the entry in the U6 wiki can be used as a starter: <https://wiki.uberspace.de/mail:maildrop>

**Comment by jdoubleu** [comment]
I'd like to write a chapter - or extend another - about `.qmail` and `maildrop`.
Are PRs welcome?

**Comment by rikroe** [comment]
> Are PRs welcome?

Judging from the fine work with uberspace/lab I'm pretty sure they are :) Would love to see a updated .qmail guide!

**Comment by luto** [comment]
PRs are always welcome! We're looking for a more specific format in the manual, though, because content here is actively supported and linked to in our website and support. Check back with @nichtmax on the rough contents and style of the new article, please :)

**Comment by nichtmax** [comment]
I'll get back to you guys in a few days, we'll need to think about the structure first.

**Comment by djbrown** [comment]
Any news on this? Are .qmail files usable in Uberspace 7 as they were in Uberspace 6 (https://wiki.uberspace.de/mail:dotqmail)?

**Comment by jonmz** [comment]
They are indeed working in exactly the same way, however we are supporting them for compatibility reasons. For future product versions we are likely to shift away from netqmail for various reasons (it is missing a _lot_ of features that are expected from a modern setup) so we are focusing on implementing `uberspace mail ...` commands that achieve the mentioned goals (forwards, catchalls, ...) but in a way we can keep _that_ interface in the future while using a fresh underlying mail system. Also we are working on enabling Sieve filters which might be a more interesting option for users instead of maildrop (which is still available). Most likely netqmail and maildrop will just stay there throughout the lifetime of U7 (= several years) while we are working on something new.

**Comment by noave** [comment]
outdated, we document only that users should not use custom qmail scripting but rely on our uberspace mail tools
