### ISSUE TITLE
exisitence of webmail is not mentioned where (probably) expected

### ISSUE THREAD

**Issue by cknoll** [Uberspace/manual#166]
The existence of <https://webmail.uberspace.de/> imho should be mentioned on relevant places like <https://dashboard.uberspace.de/dashboard/mail> and <https://dashboard.uberspace.de/dashboard/datasheet>.

**Comment by noave** [comment]
I opened an internal issue for this, thanks!

**Comment by cknoll** [comment]
For transparency: it might be useful if this public issue remains open (and thus visible) until the internal issue is fixed.

**Comment by SalocinHB** [comment]
This is the issue tracker for the manual, where the Webmail _is_ mentioned.

**Comment by noave** [comment]
hey @cknoll, I can understand that this would be interesting to cover here, but because the manual repo is no general Uberspace issue tracker (which we don't have) and this issue does not cover a problem in the manual we tend to close those kind of issues here and work on it in our internal Gitlab repos.

However, for now I can tell you that we now added a link to the manual mail access page on https://dashboard.uberspace.de/dashboard/mail to show the best way to the information how to access the mailsystem (inclusive webmail). So again, thanks for your suggestion :slightly_smiling_face: 

If you have more ideas apart from the manual or lab, we are happy to hear about at hallo@uberspace.de
