### ISSUE TITLE
include information on pricing scheme

### ISSUE THREAD

**Issue by pascoda** [Uberspace/manual#195]
at https://dashboard.uberspace.de/prices in the section "wie bezahlen", there are several links to pages in the dokuwiki/u6-wiki. 

that information could be provided in the manual, and the links should be updated.

**Comment by luto** [comment]
The business aspects (how much is it? when do you pay? which payment methods are available? what happens if I don't pay? and so on) is a bit under-documented right now. The old wiki was split into two technical doc sites: manual (out stuff) and lab (other stuff), but neither has any meta-documentation like pricing right now.

Where does that information go? Manual? Website? Dashboard? A dedicated 3rd site?

**Comment by SalocinHB** [comment]
Website

**Comment by noave** [comment]
fixed by #227
