### ISSUE TITLE
mail forward listing works for forwards, but not for mailboxes

### ISSUE THREAD

**Issue by quantumbeat** [Uberspace/manual#298]
dot-qmail configuration was a charm to work with. Transparent human-readable text files.

With the move away from qmail, the commands on https://manual.uberspace.de/mail-forwarding/ can be used.

It is possible to list the forwards (where does the forwarded mail end up), i.e. it can be listed for the forward itself.

So far so good. But.

Issue: it is not documented how to list *all* forwards that end up in a given mailbox. 

It could work similar to 

    uberspace mail user forward list forwardme

e.g.

    uberspace mail user forward list [mailbox that catches the forwards]

but it does not.

**Comment by noave** [comment]
sorry for the late response thanks for the suggestion, we have an open issue for U7 for this. Because we are working on the whole email system and also the uberspace mail commands this specific issue could not be fixed until now. 

Because this not a manual issue I will close the issue here now, we will publish a fix in our changelog (https://manual.uberspace.de)  of course if you want to keep track.
