### ISSUE TITLE
Email forwarding: Clarify local vs. full email addresses with domain

### ISSUE THREAD

**Issue by nobias** [Uberspace/manual#397]
Hi! From the page about email forwarding, it is not clear to me whether `uberspace mail user forward set <mailuser> <mail address>` works for local forwarding, too. So, if I have a local mailbox called "foo" and I would like to create a local alias "bar" for that mailbox, would `uberspace mail user forward set foo bar` do the job, or would I have to do `uberspace mail user forward set foo bar@USERNAME.uber.space`? Please clarify. Thanks!

**Comment by noave** [comment]
That is actually a bit more complex, because `uberspace mail user forward set foo bar` would only work with spamfolder disabled. Anyway, if you use `uberspace mail user forward set foo bar@USERNAME.uber.space` it will always work and will also be delivered locally in the sense, that the host does not send it over the internet to itself, but knows that it has to be delivered locally.

Because the uberspace command is noted here with `<mail address>` this is quite clear I guess. But I see that we do not enforce mailaddresses within the command and that we can mention in the manual that you may use this format for "internal" forwards as well.

**Comment by noave** [comment]
> But I see that we do not enforce mailaddresses within the command 

we have an internal issue for this now

> and that we can mention in the manual that you may use this format for "internal" forwards as well.

I updated the mail forwarding page and this is mentioned there now as well ` You may also use this command to create an internal alias, but you always have to specify the full mailaddress.` https://manual.uberspace.de/mail-forwarding/
